In [1]:
import numpy as np 
import cv2 as cv
import queue, threading, time 
from configparser import ConfigParser
from numpy.core.numeric import zeros_like
import matplotlib.pyplot as plt
import colorsys
import math
import random
from vidgear.gears import VideoGear
from vidgear.gears import WriteGear

print("import success!")

import success!


In [2]:
# 将矩阵中所有元素cos或者sin
a1 = np.array([[1,2, math.pi],[4,5,6]])

print(np.sin(a1), np.cos(a1))

[[ 8.41470985e-01  9.09297427e-01  1.22464680e-16]
 [-7.56802495e-01 -9.58924275e-01 -2.79415498e-01]] [[ 0.54030231 -0.41614684 -1.        ]
 [-0.65364362  0.28366219  0.96017029]]


In [3]:
# horizontal noise & vertical noise
filepath = "Save_20220401_121624"
mag = np.loadtxt(filepath + "/mag.txt")
angle = np.loadtxt(filepath + "/angle.txt")
print(mag.shape, angle.shape)
print(np.max(mag), np.average(mag))
print(np.max(angle), np.average(angle))
# print(txtfile[550:600, 550:600])
# 计算水平噪声和竖直噪声
horizontalNoise = np.average(np.multiply(mag, np.sin(angle)))
verticalNoise = np.average(np.multiply(mag, np.cos(angle)))
# 绝对值计算水平噪声和竖直噪声
horizontalAbsNoise = np.average(np.abs(np.multiply(mag, np.sin(angle))))
verticalAbsNoise = np.average(np.abs(np.multiply(mag, np.cos(angle))))
print("horizontalNoise is ", horizontalNoise)
print("verticalNoise is ", verticalNoise)
print("horizontalAbsNoise is ", horizontalAbsNoise)
print("verticalAbsNoise is ", verticalAbsNoise)

(544, 592) (544, 592)
2.1091604232788086 0.10282675359129945
6.2831854820251465 3.062101394713542
horizontalNoise is  -0.011222208609770735
verticalNoise is  -0.0277624687950537
horizontalAbsNoise is  0.060605622398516884
verticalAbsNoise is  0.0684613424828138


In [4]:
# read and save in Excel
#第一步：调用pandas包
timeNow = "2022"
data = list(range(1, 100))
# import pandas as pd
import os
import time
import csv
print(os.getcwd() + r"\tVariance_" + timeNow)
print(os.path.exists(os.getcwd() + r"\tVariance_" + timeNow))
# 第二步：读取数据
if not os.path.exists(os.getcwd() + r"\tVariance_" + timeNow):
    os.makedirs("tVariance_" + timeNow)
with open("tVariance_" + timeNow + '/test1.csv','w',newline='')as csv_file:
    # 获取一个csv对象进行内容写入
    writer=csv.writer(csv_file)
    for row in data:
        # writerow 写入一行数据
        writer.writerow(['xlsx', row])

d:\Desktop\BOS-PIV\program\20210731FLOW01\tVariance_2022
False
